name: Publish

on:
  push:
    branches: [ "master" ]
  schedule:
      - cron: "0 6 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-test
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Build new image
        run: |
          docker build -t templater --build-arg BASE_URL=https://test.moradev.dev/apps/templater .

      - name: Restart container
        if: always()
        run: |
          docker stop templater || true
          docker rm templater || true
          docker run -d --restart unless-stopped --name templater -p 45775:45775 templater