name: Publish

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-test
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Stop old container
        run: |
          docker stop templater || true
      
      - name: Build new image
        run: |
          docker build -t templater .

      - name: Start new container
        run: |
          docker run -d --rm --name templater -p 45775:45775 templater